sg -docs and docs qa commit
ucsb-cs156-w22/team02-w22-5pm-2 pull request #21
Opened 2022-01-31 21:45 UTC by ScottUCSB

# Overview

In a sentence or two, provide an overview of how this pull request updates the main branch.  You may use a bullet list if that helps.

# Issues Addressed

If this PR closes or deals with issues, mention them and tag the issue number with the `#` syntax.

# Details

Where applicable, include "before" and "after" screenshots or animated GIFs.   The tool [LiceCAP](https://www.cockos.com/licecap/) or one of [these similar tools](https://www.nextofwindows.com/5-free-tools-to-screen-capture-to-gif-on-windows) 
can be used to capture screenshots/animated GIFs.

## Reminders (delete this section before merging or as code is merged)
- [ ] Explicitly link to this pull request each issue that it closes
- [ ] Assign one and ideally two reviewers to review this pull request. 
- [ ] Reviewers should not just approve with "Looks good!" Instead, reviewers should carefully go through the code and use GitHub's reviewer interface to ask questions, make comments, and suggest changes.

2022-01-31 21:47 UTC, ScottUCSB commented
This is the pull request that should setup the storybook script.

2022-01-31 21:56 UTC, andrewpengucsb approved these changes
LGTM

2022-01-31 21:58 UTC, andrewpengucsb requested changes

2022-01-31 21:58 UTC, andrewpengucsb commented on README.md
> +* QA: <https://github.com/ucsb-cs156-w22/team02-w22-5pm-2-docs-qa/>
Actually I think these are the wrong links. These are links to the github repos and not the storybook websites.

2022-02-02 01:12 UTC, ScottUCSB reviewed
Yes, good catch! Thank you.

2022-02-02 01:20 UTC, andrewpengucsb approved these changes
LGTM

2022-02-02 01:20 UTC, merged